# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2bf9428317732d7b5d09e4023d1d5ecff29d016850dadbda9dc2829ca7f131a3b50f3075088a4624f45def584267da636e56f001d5b09aaa351156dc45ba5330

test:
  secret_key_base: 09d2490472507d3375e423eb358b17289ae416a797201006a7b4d80e2ab92186a35154fa852d9d320a87d0d19978cc37e5b898e83b4737ad7245297f6a252b36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
